### ISSUE TITLE
Update card UI to handle new emergency messages

### ISSUE THREAD

**Issue by timhitchins** [timhitchins/rose-city-resource#21]
The Card component needs to update to handle new emergency messages.   Below are examples of the current UI.  Hopefully we can just use what is already there.  
![image](https://user-images.githubusercontent.com/10737214/93007016-63c38680-f518-11ea-81df-de12e5e6573f.png)
![image](https://user-images.githubusercontent.com/10737214/93007008-48f11200-f518-11ea-97f4-3cefd08449f5.png)
![image](https://user-images.githubusercontent.com/10737214/93007013-56a69780-f518-11ea-93a2-3b5edcc8727e.png)

Things to consider:
- random message strings will need to be handled
- string length may be an issue

cc @isthewhiz @wrunion

**Comment by isthewhiz** [comment]
Looking into this one, let me know if someone else is already working on this?

**Comment by timhitchins** [comment]
Great @isthewhiz .  My thoughts-- `covid_message` was already changed to `emergency_message` in the Aritable and the NODE DB.  I changed the textMap in PR #23 to reflect this. The trick now will be figuring out where to put the emergency message on the card and/or if we can use the same UI that shows the emergency message already.

**Comment by isthewhiz** [comment]
I think adding in between service discrimination and hours would be good.

**Comment by isthewhiz** [comment]
Ill be adding new emergency message to results/cards.js/line 231? where are the emergency messages located?  I need to see what they consist of in order to manage them.

**Comment by isthewhiz** [comment]
it seems to me that i have every thing set up in the DB as the pull request implies what i need is to figure out my emergence message.  <div className="card-content">
                {textMap.parsedCOVID === " SOME FIRE Message " ? (
                  <div className="covid-item">CLOSED</div>   I'm I on the right track or off ?

**Comment by isthewhiz** [comment]
Moved all emergency messages in one location in between the service discrimination and hours. All covid and emergency are now displayed there. Done

**Comment by timhitchins** [comment]
After thinking more about it.  We are going to split up `covid_message` and `emergency_message` into 2 separate fields.  cc @isthewhiz

**Comment by isthewhiz** [comment]
![testbelowEMfield](https://user-images.githubusercontent.com/48775290/93275273-56550900-f771-11ea-878e-645738aa862a.JPG)
I added the  changes to the css now I'm adding those chages to the for parsedmessage. Which it did break the code and im testing it again.

**Comment by isthewhiz** [comment]
![image](https://user-images.githubusercontent.com/48775290/93275697-73d6a280-f772-11ea-8961-40f2a463a748.png)

THink im done, let me know if this works

**Comment by timhitchins** [comment]
@isthewhiz From a glance, it looks like the fire assistance resources renders twice and the message and the emergency message is in red rather than the title.  Also, submit a PR or I can't check your code.
